AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  coderoad-lab-3-prj
  Fixed circular dependency for S3 -> Lambda -> SQS -> Lambda architecture.

Resources:
  # Lambda layer for shared Python dependencies
  PythonDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: coderoad-lab-3-python-deps
      ContentUri: src/python_deps/
      CompatibleRuntimes:
        - python3.11

  # Explicitly defined S3 Bucket
  IngestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "coderoad-lab-3-ingest-bucket-${AWS::AccountId}-${AWS::Region}"
      # Notification is handled here to prevent the SAM circular loop
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt IngestFunction.Arn

  # Permission for S3 to trigger the Ingest Lambda
  AllowS3ToInvokeIngestFunction:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref IngestFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::coderoad-lab-3-ingest-bucket-${AWS::AccountId}-${AWS::Region}"

  IngestFunction:   
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: coderoad-lab-3-ingest-function
      Handler: ingest_function.index.handler
      Runtime: python3.11
      CodeUri: src/
      Layers:
        - !Ref PythonDependenciesLayer
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          METADATA_QUEUE_URL: !Ref MetadataQueue
      Policies:
        # Using SAM Policy Templates to avoid circular ARN references
        - S3ReadPolicy:
            BucketName: !Sub "coderoad-lab-3-ingest-bucket-${AWS::AccountId}-${AWS::Region}"
        - SQSSendMessagePolicy:
            QueueName: !GetAtt MetadataQueue.QueueName

  MetadataQueue:
    Type: AWS::SQS::Queue 
    Properties:
      QueueName: coderoad-lab-3-metadata-queue
      VisibilityTimeout: 120

  MetadataFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: coderoad-lab-3-metadata-function
      Handler: metadata_function.index.handler
      Runtime: python3.11
      CodeUri: src/
      Layers:
        - !Ref PythonDependenciesLayer
      Timeout: 60
      MemorySize: 512
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub "coderoad-lab-3-ingest-bucket-${AWS::AccountId}-${AWS::Region}"
        - S3WritePolicy:
            BucketName: !Sub "coderoad-lab-3-ingest-bucket-${AWS::AccountId}-${AWS::Region}"
        - SQSPollerPolicy:
            QueueName: !GetAtt MetadataQueue.QueueName
      Events:
        SQSMetaEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MetadataQueue.Arn
            BatchSize: 1

Outputs:
  BucketName:
    Value: !Ref IngestBucket
  MetadataQueueURL:
    Value: !Ref MetadataQueue
  IngestFunctionName:
    Value: !Ref IngestFunction
  MetadataFunctionName:
    Value: !Ref MetadataFunction